In [1]:
import os
os.listdir('D:\Dimas File\Belajar\Machine Learning')

['archive.zip',
 'database.sqlite',
 'Iris.csv',
 'jumlah-wajib-pajak-dikelola-dan-terdaftar-kkp-pratama-2020.xlsx',
 'Latihan1-Konversi Pandas Dataframe.ipynb',
 'Latihan2-Sklearn Train Test Split.ipynb',
 'Latihan3-Sklearn Cross Validation Split.ipynb',
 'Latihan4-Sklearn Decission Tree.ipynb',
 'Latihan5-Sklearn Linear Regression.ipynb',
 'tingkat-pengangguran-terbuka-tpt-dan-tingkat-partisipasi-angkatan-kerja-tpak-menurut-kabkota-di-.csv']

In [4]:
import pandas as pd
df = pd.read_csv('D:\Dimas File\Belajar\Machine Learning\iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa